version: "3"

services:

  ecommerce-mom:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=super
    ports:
      # Protocol port
      - "5672:5672"
      # Management UI
      - "8083:15672"

  ecommerce-db:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce-demo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - mongodb_data:/data/db
      - ./config/ecommerce-db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ecommerce-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: super
    depends_on:
      - ecommerce-db

volumes:
  mongodb_data: